name: Python examples CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        example:
          - openai
          - gemini
          - claude
          - kiro
          - general-agent
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          cd examples/${{ matrix.example }}
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run tests
        run: |
          cd examples/${{ matrix.example }}
          if [ -d tests ]; then python -m pytest -q; fi
