name: Python examples CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        example:
          - cli-agent-examples/openai
          - cli-agent-examples/gemini
          - cli-agent-examples/claude
          - cli-agent-examples/general-agent
          - ai-ide-examples/kiro
          - ai-ide-examples/cursor
          - ai-ide-examples/windsurf
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          cd ${{ matrix.example }}
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run tests
        run: |
          cd ${{ matrix.example }}
          if [ -d tests ]; then python -m pytest -q; fi
